title: MCPT Battlesnake Docs
description: Documentation for getting ready for the MCPT Battlesnake Tournament!
theme: just-the-docs

url: https://battlesnake.mcpt.jimmyliu.dev

aux_links:
  Official Battlesnake Site: https://play.battlesnake.com/
